nohup: ignoring input
[2025-03-16 11:10:38 +0000] [29277] [INFO] Starting gunicorn 23.0.0
[2025-03-16 11:10:38 +0000] [29277] [INFO] Listening at: http://0.0.0.0:5000 (29277)
[2025-03-16 11:10:38 +0000] [29277] [INFO] Using worker: sync
[2025-03-16 11:10:38 +0000] [29278] [INFO] Booting worker with pid: 29278
[2025-03-16 11:10:38 +0000] [29279] [INFO] Booting worker with pid: 29279
[2025-03-16 11:10:38 +0000] [29280] [INFO] Booting worker with pid: 29280
[2025-03-16 11:10:38 +0000] [29281] [INFO] Booting worker with pid: 29281
[2025-03-16 11:10:38 +0000] [29279] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/DevOps1/app.py", line 4, in <module>
    log = logging.getLogger('werkzeug')
          ^^^^^^^^^^^^^^^^^
AttributeError: module 'flask.logging' has no attribute 'getLogger'
[2025-03-16 11:10:38 +0000] [29279] [INFO] Worker exiting (pid: 29279)
[2025-03-16 11:10:38 +0000] [29278] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/DevOps1/app.py", line 4, in <module>
    log = logging.getLogger('werkzeug')
          ^^^^^^^^^^^^^^^^^
AttributeError: module 'flask.logging' has no attribute 'getLogger'
[2025-03-16 11:10:38 +0000] [29278] [INFO] Worker exiting (pid: 29278)
[2025-03-16 11:10:38 +0000] [29280] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/DevOps1/app.py", line 4, in <module>
    log = logging.getLogger('werkzeug')
          ^^^^^^^^^^^^^^^^^
AttributeError: module 'flask.logging' has no attribute 'getLogger'
[2025-03-16 11:10:38 +0000] [29280] [INFO] Worker exiting (pid: 29280)
[2025-03-16 11:10:38 +0000] [29281] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DevOps1/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/DevOps1/app.py", line 4, in <module>
    log = logging.getLogger('werkzeug')
          ^^^^^^^^^^^^^^^^^
AttributeError: module 'flask.logging' has no attribute 'getLogger'
[2025-03-16 11:10:38 +0000] [29281] [INFO] Worker exiting (pid: 29281)
[2025-03-16 11:10:38 +0000] [29277] [ERROR] Worker (pid:29280) exited with code 3
[2025-03-16 11:10:38 +0000] [29277] [ERROR] Worker (pid:29279) was sent SIGTERM!
[2025-03-16 11:10:38 +0000] [29277] [ERROR] Worker (pid:29281) was sent SIGTERM!
[2025-03-16 11:10:38 +0000] [29277] [ERROR] Worker (pid:29278) was sent SIGTERM!
[2025-03-16 11:10:38 +0000] [29277] [ERROR] Shutting down: Master
[2025-03-16 11:10:38 +0000] [29277] [ERROR] Reason: Worker failed to boot.
